Setup api tests
ya-pekatoros/task-manager-django pull request #25
Opened 2023-03-09 04:22 UTC by ya-pekatoros

2023-03-09 14:47 UTC, aleksandr-semenov-dbp requested changes

2023-03-09 14:47 UTC, aleksandr-semenov-dbp commented on task_manager/main/test/test_tag.py
> +        assert json.loads(response.content.decode("utf-8")) == expected_response
плохо повторять много раз одно и то же - `json.loads(response.content.decode("utf-8"))` Если я не ошибаюсь, у response уже есть метод response.json() который все это делает.

2023-03-09 14:47 UTC, aleksandr-semenov-dbp commented on task_manager/main/test/test_tag.py
> +        print(self.tag)
отладочные printы удаляем из кода

2023-03-09 14:47 UTC, aleksandr-semenov-dbp commented on task_manager/main/test/base.py
> +            cls.user = cls.create_api_user(cls.user_attributes)
Лучше не создавать такие объекты по умолчанию, для более сложных тесткейсов где надо соблюсти/пересчитать количество объектов эти могут оказаться неожиданными. Можно сделать отдельную функцию для такого создания, но запускать это нужно явно в каждом тесткейсе

2023-03-10 04:24 UTC, ya-pekatoros commented on task_manager/main/test/test_tag.py
> +        print(self.tag)
да, пропустил....

2023-03-10 04:29 UTC, ya-pekatoros commented on task_manager/main/test/base.py
> +            cls.user = cls.create_api_user(cls.user_attributes)
То есть мы в каждом классе в тестах должны переопределив setupdate добавить то, что нужно? или вызывать функции создания сущностей в каждой тестовой функции (где тестируем операции)? во втором случае кода станет больше, каждый раз будем вызывать создание тасков/юзеров.

2023-03-10 04:45 UTC, ya-pekatoros commented on task_manager/main/test/test_tag.py
> +        assert json.loads(response.content.decode("utf-8")) == expected_response
действительно) заменил, спасибо!

2023-03-14 14:06 UTC, aleksandr-semenov-dbp requested changes

2023-03-14 14:06 UTC, aleksandr-semenov-dbp commented on task_manager/main/test/test_tag.py
> +    def test_list(self):
В тесте листа надо создать хотя бы 2-3 объекта, и проверить что вернулись эти же объекты.

2023-03-14 14:06 UTC, aleksandr-semenov-dbp commented on task_manager/main/test/test_tag.py
> +        assert response.json()[0] == expected_response
Надо создать хотя бы два объекта и проверить что list возвращает именно их

2023-03-14 14:06 UTC, aleksandr-semenov-dbp commented on task_manager/main/test/test_tag.py
> +        assert response.status_code == HTTPStatus.NO_CONTENT, response.content
Проверить http-код недостаточно, обычно здесь мы создаем 2 обекта, удаляем 1 и проверяем что list возвращает список из только второго объекта

2023-03-17 06:34 UTC, aleksandr-semenov-dbp approved these changes

2023-03-18 03:58 UTC, merged