Setup adminpanel for models
ya-pekatoros/task-manager-django pull request #7
Opened 2023-03-02 05:39 UTC by ya-pekatoros

2023-03-04 10:40 UTC, aleksandr-semenov-dbp requested changes

2023-03-04 10:40 UTC, aleksandr-semenov-dbp commented on task_manager/main/admin.py
> +<<<<<<< Updated upstream
чтото поломалось

2023-03-04 11:36 UTC, ya-pekatoros commented on task_manager/main/admin.py
> +<<<<<<< Updated upstream
да, обновлял ветки и немного запутался, исправлю

2023-03-04 12:50 UTC, ya-pekatoros commented on task_manager/main/admin.py
> +<<<<<<< Updated upstream
Правки внес коммитом.

2023-03-06 05:01 UTC, aleksandr-semenov-dbp approved these changes

2023-03-06 12:38 UTC, merged